### ISSUE TITLE
crash on running

### ISSUE THREAD

**Issue by xackery** [LanternEQ/LanternExtractor#1]
> LanternExtractor neriaka

EQ Client: RoF2

Unhandled Exception: System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(Stream stream)
   at LanternExtractor.Infrastructure.ImageWriter.WriteImage(Stream bytes, String filePath, String fileName, ShaderType type)
   at LanternExtractor.EQ.Pfs.PfsArchive.WriteImage(Int32 index, ShaderType type, String folderName)
   at LanternExtractor.EQ.Pfs.PfsArchive.WriteAllFiles(Dictionary`2 textureTypes, String folderName, Boolean onlyTextures)
   at LanternExtractor.LanternExtractor.ExtractZoneFile(String shortName)
   at LanternExtractor.LanternExtractor.ExtractZone(String shortName)
   at LanternExtractor.LanternExtractor.Main(String[] args)

**Comment by xackery** [comment]
[log.zip](https://github.com/danwilkins/LanternExtractor/files/2849670/log.zip)

**Comment by danwilkins** [comment]
Thanks for the report. Are you able to extract any zone or is this error thrown every time?

**Comment by xackery** [comment]
Sorry, I didn't see this reply. Data did indeed extract, obj files and such, I didn't try opening them just yet (maya isnt' installed). This error happens on every zone I picked (random classic zones like neriaka, ecommons, freportw, etc). I can't fully tell if it was a false alarm or failure since I don't have the product working to compare. if nobody else reports though not a huge deal for now

**Comment by ghronkrepps** [comment]
Also getting the issue on files from a live EQ install. I do not have any previous versions to test on yet.

**When I turn wld off it works.**

The error is happening on `var image = new Bitmap(bytes);`

From MSDN ArgumentException occurs

> ArgumentException
> 
> stream does not contain image data or is null.
> 
> -or-
> 
> stream contains a PNG image file with a single dimension greater than 65,535 pixels.

I'm guessing the format is different in newer versions.

**Comment by MickWPM** [comment]
@danwilkins I encountered the same issue and have done some experimenting.

ROF2 and P99 clients are both throwing errors when trying to create bitmaps of certain streams. The streams that throw the error all have the same header (68, 68, 83, 32, 124, 0, 0, 0, 7, 16, 10, 0) which I believe from some quick googling might be DDS (DirectDraw Surface) files. The images successfully written are 66, 77, ... headers (BM...) which I believe is the header for varying bitmap files.

Of note as mentioned above, it only has the errors when ExtractWld is flagged as true. When set to false in settings there are no errors.

**Comment by danwilkins** [comment]
@MickWPM Hey Mick. Yes, this is a problem on my end. I wrote this extractor for the old EQ zone versions. I'll add experimental extraction support for the post Luclin/live client in the next release.

**Comment by MickWPM** [comment]
> @MickWPM Hey Mick. Yes, this is a problem on my end. I wrote this extractor for the old EQ zone versions. I'll add experimental extraction support for the post Luclin/live client in the next release.

@danwilkins Oops my bad, forgot the P99 client runs on a much later build (dont have original CDs anymore). Thanks for the reply. 
Do you mind if I flick you a brief email using your github email?

**Comment by danwilkins** [comment]
Had time to take a look at this. Modern zones use the DDS format for textures. I added support for the extracting of _some_ newer zones and their textures and models in the `development/0.2.0` branch. I will continue to work on this. At some point, they switched from S3D archives to EQG and I haven't taken a look into what's involved in extracting this file type.

@MickWPM Please, feel free to send me an e-mail.

**Comment by danwilkins** [comment]
@xackery Try again if you would with `neriaka` using the `development/0.2.0` branch. This is an older style zone format so the only difference should be that they use .dds textures.
