### ISSUE TITLE
Material cannot be assigned

### ISSUE THREAD

**Issue by Impact1983** [LanternEQ/LanternExtractor#10]
First off.... literally amazing project.  Hats off, man.  This is beyond amazing.  I don't know if you're still working on this at all but I went through every classic zone and these are the errors I had.  If the zone isn't listed below it processed perfectly:

G:\LanternExtractor\LanternExtractor\bin\Release>LanternExtractor frozenshadow
Material cannot be assigned: ABHCLK401_MDF
Material cannot be assigned: ABHCLK0402_MDF
Material cannot be assigned: ABHCLK0405_MDF
Material cannot be assigned: ABHCLK0404_MDF
Material cannot be assigned: ABHCLK0403_MDF
Error dealing with mesh: GOMBI_L_DMSPRITEDEF
Mesh is not valid: GOMBI_L_DMSPRITEDEF
Error dealing with mesh: GOMBI_L_DMSPRITEDEF
Mesh is not valid: GOMBI_L_DMSPRITEDEF
Error dealing with mesh: GOMFO_L_DMSPRITEDEF
Mesh is not valid: GOMFO_L_DMSPRITEDEF
Error dealing with mesh: GOMFO_L_DMSPRITEDEF
Mesh is not valid: GOMFO_L_DMSPRITEDEF

G:\LanternExtractor\LanternExtractor\bin\Release>LanternExtractor butcher
Material cannot be assigned: KAMHELM01_MDF
Material cannot be assigned: PRECRATE2_MDF
Material cannot be assigned: PRECRATE1_MDF
Material cannot be assigned: BOATSIDE2_MDF
Material cannot be assigned: DHCEILING_MDF
Error dealing with mesh: PREPE_DMSPRITEDEF
Mesh is not valid: PREPE_DMSPRITEDEF
Error dealing with mesh: PREPE_DMSPRITEDEF
Mesh is not valid: PREPE_DMSPRITEDEF

G:\LanternExtractor\LanternExtractor\bin\Release>LanternExtractor freportn
Material cannot be assigned: KITESHIELD-M_MDF
Material cannot be assigned: KITESHIELD-MBACK_MDF
Material cannot be assigned: SWORDHANDLE_MDF
Material cannot be assigned: SCIM-HILT_MDF
Material cannot be assigned: SCIM-HANDLE_MDF
Material cannot be assigned: WIDETIP-HILT_MDF
Material cannot be assigned: WIDETIP-HANDLE_MDF
Material cannot be assigned: WIDETIP-BLADE_MDF
Material cannot be assigned: DAGGAURD2_MDF
Material cannot be assigned: AXEHANDLE_MDF
Material cannot be assigned: AXE2BLDPOINT_MDF
Material cannot be assigned: AXE2BLDHANDLE_MDF
Material cannot be assigned: SHIELDROUND-METALBACK_MDF
Material cannot be assigned: SHIELDROUND-METAL_MDF

G:\LanternExtractor\LanternExtractor\bin\Release>LanternExtractor freporte
Material cannot be assigned: KITESHIELD-M_MDF
Material cannot be assigned: KITESHIELD-MBACK_MDF
Material cannot be assigned: SWORDHANDLE_MDF
Material cannot be assigned: SCIM-HILT_MDF
Material cannot be assigned: SCIM-HANDLE_MDF
Material cannot be assigned: WIDETIP-HILT_MDF
Material cannot be assigned: WIDETIP-HANDLE_MDF
Material cannot be assigned: WIDETIP-BLADE_MDF
Material cannot be assigned: DAGGAURD2_MDF
Material cannot be assigned: AXEHANDLE_MDF
Material cannot be assigned: AXE2BLDPOINT_MDF
Material cannot be assigned: AXE2BLDHANDLE_MDF
Material cannot be assigned: SHIELDROUND-METALBACK_MDF
Material cannot be assigned: SHIELDROUND-METAL_MDF
Material cannot be assigned: PRECRATE2_MDF
Material cannot be assigned: PRECRATE1_MDF
Material cannot be assigned: BOATSIDE2_MDF
Material cannot be assigned: DHCEILING_MDF
Error dealing with mesh: PREPE_DMSPRITEDEF
Mesh is not valid: PREPE_DMSPRITEDEF
Error dealing with mesh: PREPE_DMSPRITEDEF
Mesh is not valid: PREPE_DMSPRITEDEF

G:\LanternExtractor\LanternExtractor\bin\Release>LanternExtractor nro
Material cannot be assigned: KITESHIELD-M_MDF
Material cannot be assigned: KITESHIELD-MBACK_MDF
Material cannot be assigned: SWORDHANDLE_MDF
Material cannot be assigned: SCIM-HILT_MDF
Material cannot be assigned: SCIM-HANDLE_MDF
Material cannot be assigned: WIDETIP-HILT_MDF
Material cannot be assigned: WIDETIP-HANDLE_MDF
Material cannot be assigned: WIDETIP-BLADE_MDF
Material cannot be assigned: DAGGAURD2_MDF
Material cannot be assigned: AXEHANDLE_MDF
Material cannot be assigned: AXE2BLDPOINT_MDF
Material cannot be assigned: AXE2BLDHANDLE_MDF
Material cannot be assigned: SHIELDROUND-METALBACK_MDF
Material cannot be assigned: SHIELDROUND-METAL_MDF

G:\LanternExtractor\LanternExtractor\bin\Release>LanternExtractor oasis
Material cannot be assigned: KITESHIELD-M_MDF
Material cannot be assigned: KITESHIELD-MBACK_MDF
Material cannot be assigned: SWORDHANDLE_MDF
Material cannot be assigned: SCIM-HILT_MDF
Material cannot be assigned: SCIM-HANDLE_MDF
Material cannot be assigned: WIDETIP-HILT_MDF
Material cannot be assigned: WIDETIP-HANDLE_MDF
Material cannot be assigned: WIDETIP-BLADE_MDF
Material cannot be assigned: DAGGAURD2_MDF
Material cannot be assigned: AXEHANDLE_MDF
Material cannot be assigned: AXE2BLDPOINT_MDF
Material cannot be assigned: AXE2BLDHANDLE_MDF
Material cannot be assigned: SHIELDROUND-METALBACK_MDF
Material cannot be assigned: SHIELDROUND-METAL_MDF

G:\LanternExtractor\LanternExtractor\bin\Release>LanternExtractor sro
Material cannot be assigned: KITESHIELD-M_MDF
Material cannot be assigned: KITESHIELD-MBACK_MDF
Material cannot be assigned: SWORDHANDLE_MDF
Material cannot be assigned: SCIM-HILT_MDF
Material cannot be assigned: SCIM-HANDLE_MDF
Material cannot be assigned: WIDETIP-HILT_MDF
Material cannot be assigned: WIDETIP-HANDLE_MDF
Material cannot be assigned: WIDETIP-BLADE_MDF
Material cannot be assigned: DAGGAURD2_MDF
Material cannot be assigned: AXEHANDLE_MDF
Material cannot be assigned: AXE2BLDPOINT_MDF
Material cannot be assigned: AXE2BLDHANDLE_MDF
Material cannot be assigned: SHIELDROUND-METALBACK_MDF
Material cannot be assigned: SHIELDROUND-METAL_MDF

G:\LanternExtractor\LanternExtractor\bin\Release>LanternExtractor gukbottom
Material cannot be assigned: MIMCHESTTOP_MDF
Material cannot be assigned: MIMCHESTSIDE1_MDF
Material cannot be assigned: MIMMOUTH02_MDF
Material cannot be assigned: MIMCHESTFRNT_MDF
Material cannot be assigned: MIMMOUTH01_MDF

G:\LanternExtractor\LanternExtractor\bin\Release>LanternExtractor oot
Material cannot be assigned: PRECRATE2_MDF
Material cannot be assigned: PRECRATE1_MDF
Material cannot be assigned: GHOSTSTERN_MDF
Material cannot be assigned: GHOSTBOW1_MDF
Material cannot be assigned: GHOSTBOATSIDE_MDF
Material cannot be assigned: GHOSTBOATSIDE2_MDF
Material cannot be assigned: GHOSTWINDER_MDF
Material cannot be assigned: GHOSTMAST_MDF
Material cannot be assigned: GHOSTMAST1_MDF
Material cannot be assigned: GHOSTDECK_MDF
Material cannot be assigned: GHOSTDHCEILING_MDF
Material cannot be assigned: GHOSTCABIN_MDF
Material cannot be assigned: GHOSTCABIN1_MDF
Material cannot be assigned: GHOSTARM2_MDF
Material cannot be assigned: GHOSTAFTWALL_MDF
Material cannot be assigned: GHOSTDHWALL_MDF
Material cannot be assigned: GHOSTMHOLE_MDF
Material cannot be assigned: GHOSTSAIL_MDF
Material cannot be assigned: GHOSTSHIPSKULL_MDF
Material cannot be assigned: BOATSIDE2_MDF
Material cannot be assigned: DHCEILING_MDF
Error dealing with mesh: PREPE_DMSPRITEDEF
Mesh is not valid: PREPE_DMSPRITEDEF
Error dealing with mesh: PREPE_DMSPRITEDEF
Mesh is not valid: PREPE_DMSPRITEDEF

G:\LanternExtractor\LanternExtractor\bin\Release>LanternExtractor lavastorm
Material cannot be assigned: KITESHIELD-M_MDF
Material cannot be assigned: KITESHIELD-MBACK_MDF
Material cannot be assigned: SWORDHANDLE_MDF
Material cannot be assigned: SCIM-HILT_MDF
Material cannot be assigned: SCIM-HANDLE_MDF
Material cannot be assigned: WIDETIP-HILT_MDF
Material cannot be assigned: WIDETIP-HANDLE_MDF
Material cannot be assigned: WIDETIP-BLADE_MDF
Material cannot be assigned: DAGGAURD2_MDF
Material cannot be assigned: AXEHANDLE_MDF
Material cannot be assigned: AXE2BLDPOINT_MDF
Material cannot be assigned: AXE2BLDHANDLE_MDF
Material cannot be assigned: SHIELDROUND-METALBACK_MDF
Material cannot be assigned: SHIELDROUND-METAL_MDF

G:\LanternExtractor\LanternExtractor\bin\Release>LanternExtractor neriakc
Material cannot be assigned: MIMCHESTTOP_MDF
Material cannot be assigned: MIMCHESTSIDE1_MDF
Material cannot be assigned: MIMMOUTH02_MDF
Material cannot be assigned: MIMCHESTFRNT_MDF
Material cannot be assigned: MIMMOUTH01_MDF

G:\LanternExtractor\LanternExtractor\bin\Release>LanternExtractor cazicthule
Material cannot be assigned: KITESHIELD-M_MDF
Material cannot be assigned: KITESHIELD-MBACK_MDF
Material cannot be assigned: SWORDHANDLE_MDF
Material cannot be assigned: SCIM-HILT_MDF
Material cannot be assigned: SCIM-HANDLE_MDF
Material cannot be assigned: WIDETIP-HILT_MDF
Material cannot be assigned: WIDETIP-HANDLE_MDF
Material cannot be assigned: WIDETIP-BLADE_MDF
Material cannot be assigned: DAGGAURD2_MDF
Material cannot be assigned: AXEHANDLE_MDF
Material cannot be assigned: AXE2BLDPOINT_MDF
Material cannot be assigned: AXE2BLDHANDLE_MDF
Material cannot be assigned: SHIELDROUND-METALBACK_MDF
Material cannot be assigned: SHIELDROUND-METAL_MDF

G:\LanternExtractor\LanternExtractor\bin\Release>LanternExtractor fearplane
Material cannot be assigned: CUBBONESUA01_MDF
Material cannot be assigned: CUBBONESCH03_MDF
Material cannot be assigned: CUBBONESFT01_MDF
Material cannot be assigned: CUBBONESFT02_MDF
Material cannot be assigned: CUBBONESLG01_MDF

G:\LanternExtractor\LanternExtractor\bin\Release>LanternExtractor hateplane
Material cannot be assigned: MIMCHESTTOP_MDF
Material cannot be assigned: MIMCHESTSIDE1_MDF
Material cannot be assigned: MIMMOUTH02_MDF
Material cannot be assigned: MIMCHESTFRNT_MDF
Material cannot be assigned: MIMMOUTH01_MDF

G:\LanternExtractor\LanternExtractor\bin\Release>LanternExtractor najena
Material cannot be assigned: MIMCHESTTOP_MDF
Material cannot be assigned: MIMCHESTSIDE1_MDF
Material cannot be assigned: MIMMOUTH02_MDF
Material cannot be assigned: MIMCHESTFRNT_MDF
Material cannot be assigned: MIMMOUTH01_MDF

G:\LanternExtractor\LanternExtractor\bin\Release>LanternExtractor lavastorm
Material cannot be assigned: KITESHIELD-M_MDF
Material cannot be assigned: KITESHIELD-MBACK_MDF
Material cannot be assigned: SWORDHANDLE_MDF
Material cannot be assigned: SCIM-HILT_MDF
Material cannot be assigned: SCIM-HANDLE_MDF
Material cannot be assigned: WIDETIP-HILT_MDF
Material cannot be assigned: WIDETIP-HANDLE_MDF
Material cannot be assigned: WIDETIP-BLADE_MDF
Material cannot be assigned: DAGGAURD2_MDF
Material cannot be assigned: AXEHANDLE_MDF
Material cannot be assigned: AXE2BLDPOINT_MDF
Material cannot be assigned: AXE2BLDHANDLE_MDF
Material cannot be assigned: SHIELDROUND-METALBACK_MDF
Material cannot be assigned: SHIELDROUND-METAL_MDF

G:\LanternExtractor\LanternExtractor\bin\Release>LanternExtractor crushbone
Material cannot be assigned: KAMHELM01_MDF

G:\LanternExtractor\LanternExtractor\bin\Release>LanternExtractor kaladima
Material cannot be assigned: KAMHELM01_MDF

G:\LanternExtractor\LanternExtractor\bin\Release>LanternExtractor kaladimb
Material cannot be assigned: KAMHELM01_MDF

G:\LanternExtractor\LanternExtractor\bin\Release>LanternExtractor unrest
Material cannot be assigned: KITESHIELD-M_MDF
Material cannot be assigned: KITESHIELD-MBACK_MDF
Material cannot be assigned: SWORDHANDLE_MDF
Material cannot be assigned: SCIM-HILT_MDF
Material cannot be assigned: SCIM-HANDLE_MDF
Material cannot be assigned: WIDETIP-HILT_MDF
Material cannot be assigned: WIDETIP-HANDLE_MDF
Material cannot be assigned: WIDETIP-BLADE_MDF
Material cannot be assigned: DAGGAURD2_MDF
Material cannot be assigned: AXEHANDLE_MDF
Material cannot be assigned: AXE2BLDPOINT_MDF
Material cannot be assigned: AXE2BLDHANDLE_MDF
Material cannot be assigned: SHIELDROUND-METALBACK_MDF
Material cannot be assigned: SHIELDROUND-METAL_MDF
Material cannot be assigned: MIMCHESTTOP_MDF
Material cannot be assigned: MIMCHESTSIDE1_MDF
Material cannot be assigned: MIMMOUTH02_MDF
Material cannot be assigned: MIMCHESTFRNT_MDF
Material cannot be assigned: MIMMOUTH01_MDF

G:\LanternExtractor\LanternExtractor\bin\Release>LanternExtractor runnyeye
Material cannot be assigned: CUBBONESUA01_MDF
Material cannot be assigned: CUBBONESCH03_MDF
Material cannot be assigned: CUBBONESFT01_MDF
Material cannot be assigned: CUBBONESFT02_MDF
Material cannot be assigned: CUBBONESLG01_MDF
Material cannot be assigned: MIMCHESTTOP_MDF
Material cannot be assigned: MIMCHESTSIDE1_MDF
Material cannot be assigned: MIMMOUTH02_MDF
Material cannot be assigned: MIMCHESTFRNT_MDF
Material cannot be assigned: MIMMOUTH01_MDF

G:\LanternExtractor\LanternExtractor\bin\Release>LanternExtractor paw
Material cannot be assigned: CUBBONESUA01_MDF
Material cannot be assigned: CUBBONESCH03_MDF
Material cannot be assigned: CUBBONESFT01_MDF
Material cannot be assigned: CUBBONESFT02_MDF
Material cannot be assigned: CUBBONESLG01_MDF

G:\LanternExtractor\LanternExtractor\bin\Release>LanternExtractor akanon
Material cannot be assigned: CUBBONESUA01_MDF
Material cannot be assigned: CUBBONESCH03_MDF
Material cannot be assigned: CUBBONESFT01_MDF
Material cannot be assigned: CUBBONESFT02_MDF
Material cannot be assigned: CUBBONESLG01_MDF

G:\LanternExtractor\LanternExtractor\bin\Release>LanternExtractor befallen
Material cannot be assigned: CUBBONESUA01_MDF
Material cannot be assigned: CUBBONESCH03_MDF
Material cannot be assigned: CUBBONESFT01_MDF
Material cannot be assigned: CUBBONESFT02_MDF
Material cannot be assigned: CUBBONESLG01_MDF
Material cannot be assigned: MIMCHESTTOP_MDF
Material cannot be assigned: MIMCHESTSIDE1_MDF
Material cannot be assigned: MIMMOUTH02_MDF
Material cannot be assigned: MIMCHESTFRNT_MDF
Material cannot be assigned: MIMMOUTH01_MDF

G:\LanternExtractor\LanternExtractor\bin\Release>LanternExtractor beholder
Material cannot be assigned: KITESHIELD-M_MDF
Material cannot be assigned: KITESHIELD-MBACK_MDF
Material cannot be assigned: SWORDHANDLE_MDF
Material cannot be assigned: SCIM-HILT_MDF
Material cannot be assigned: SCIM-HANDLE_MDF
Material cannot be assigned: WIDETIP-HILT_MDF
Material cannot be assigned: WIDETIP-HANDLE_MDF
Material cannot be assigned: WIDETIP-BLADE_MDF
Material cannot be assigned: DAGGAURD2_MDF
Material cannot be assigned: AXEHANDLE_MDF
Material cannot be assigned: AXE2BLDPOINT_MDF
Material cannot be assigned: AXE2BLDHANDLE_MDF
Material cannot be assigned: SHIELDROUND-METALBACK_MDF
Material cannot be assigned: SHIELDROUND-METAL_MDF

G:\LanternExtractor\LanternExtractor\bin\Release>LanternExtractor blackburrow
Material cannot be assigned: MIMCHESTTOP_MDF
Material cannot be assigned: MIMCHESTSIDE1_MDF
Material cannot be assigned: MIMMOUTH02_MDF
Material cannot be assigned: MIMCHESTFRNT_MDF
Material cannot be assigned: MIMMOUTH01_MDF

G:\LanternExtractor\LanternExtractor\bin\Release>LanternExtractor crushbone
Material cannot be assigned: KAMHELM01_MDF

G:\LanternExtractor\LanternExtractor\bin\Release>LanternExtractor erudnext
Material cannot be assigned: PRECRATE2_MDF
Material cannot be assigned: PRECRATE1_MDF
Material cannot be assigned: ERBEDSIDE_MDF
Material cannot be assigned: BOATSIDE2_MDF
Material cannot be assigned: DHCEILING_MDF
Error dealing with mesh: PREPE_DMSPRITEDEF
Mesh is not valid: PREPE_DMSPRITEDEF
Error dealing with mesh: PREPE_DMSPRITEDEF
Mesh is not valid: PREPE_DMSPRITEDEF

G:\LanternExtractor\LanternExtractor\bin\Release>LanternExtractor mistmoore
Material cannot be assigned: MIMCHESTTOP_MDF
Material cannot be assigned: MIMCHESTSIDE1_MDF
Material cannot be assigned: MIMMOUTH02_MDF
Material cannot be assigned: MIMCHESTFRNT_MDF
Material cannot be assigned: MIMMOUTH01_MDF

G:\LanternExtractor\LanternExtractor\bin\Release>LanternExtractor najena
Material cannot be assigned: MIMCHESTTOP_MDF
Material cannot be assigned: MIMCHESTSIDE1_MDF
Material cannot be assigned: MIMMOUTH02_MDF
Material cannot be assigned: MIMCHESTFRNT_MDF
Material cannot be assigned: MIMMOUTH01_MDF

G:\LanternExtractor\LanternExtractor\bin\Release>LanternExtractor qcat
Material cannot be assigned: CUBBONESUA01_MDF
Material cannot be assigned: CUBBONESCH03_MDF
Material cannot be assigned: CUBBONESFT01_MDF
Material cannot be assigned: CUBBONESFT02_MDF
Material cannot be assigned: CUBBONESLG01_MDF

G:\LanternExtractor\LanternExtractor\bin\Release>LanternExtractor qeynos
Material cannot be assigned: PRECRATE2_MDF
Material cannot be assigned: PRECRATE1_MDF
Material cannot be assigned: BOATSIDE2_MDF
Material cannot be assigned: DHCEILING_MDF
Error dealing with mesh: PREPE_DMSPRITEDEF
Mesh is not valid: PREPE_DMSPRITEDEF
Error dealing with mesh: PREPE_DMSPRITEDEF
Mesh is not valid: PREPE_DMSPRITEDEF

G:\LanternExtractor\LanternExtractor\bin\Release>LanternExtractor runnyeye
Material cannot be assigned: CUBBONESUA01_MDF
Material cannot be assigned: CUBBONESCH03_MDF
Material cannot be assigned: CUBBONESFT01_MDF
Material cannot be assigned: CUBBONESFT02_MDF
Material cannot be assigned: CUBBONESLG01_MDF
Material cannot be assigned: MIMCHESTTOP_MDF
Material cannot be assigned: MIMCHESTSIDE1_MDF
Material cannot be assigned: MIMMOUTH02_MDF
Material cannot be assigned: MIMCHESTFRNT_MDF
Material cannot be assigned: MIMMOUTH01_MDF

G:\LanternExtractor\LanternExtractor\bin\Release>LanternExtractor unrest
Material cannot be assigned: KITESHIELD-M_MDF
Material cannot be assigned: KITESHIELD-MBACK_MDF
Material cannot be assigned: SWORDHANDLE_MDF
Material cannot be assigned: SCIM-HILT_MDF
Material cannot be assigned: SCIM-HANDLE_MDF
Material cannot be assigned: WIDETIP-HILT_MDF
Material cannot be assigned: WIDETIP-HANDLE_MDF
Material cannot be assigned: WIDETIP-BLADE_MDF
Material cannot be assigned: DAGGAURD2_MDF
Material cannot be assigned: AXEHANDLE_MDF
Material cannot be assigned: AXE2BLDPOINT_MDF
Material cannot be assigned: AXE2BLDHANDLE_MDF
Material cannot be assigned: SHIELDROUND-METALBACK_MDF
Material cannot be assigned: SHIELDROUND-METAL_MDF
Material cannot be assigned: MIMCHESTTOP_MDF
Material cannot be assigned: MIMCHESTSIDE1_MDF
Material cannot be assigned: MIMMOUTH02_MDF
Material cannot be assigned: MIMCHESTFRNT_MDF
Material cannot be assigned: MIMMOUTH01_MDF

**Comment by danwilkins** [comment]
Please use new `0.1.5` version and let me know if you run into issues.
