### ISSUE TITLE
unfriendly console system

### ISSUE THREAD

**Issue by xackery** [LanternEQ/LanternExtractor#2]
1) When you run the executable via double click, the window simply closes with no prompt. (I know in go world we have a neat tool called mousetrap to help with this - https://github.com/inconshreveable/mousetrap)

2) stdout doesn't echo out errors, you have to open up logs.txt to get any data. E.g. console was empty, but logs noted generic <shortname> usage (I hadn't provided parameters).

**Comment by danwilkins** [comment]
This has been improved. Will be released in the new 0.2 version. Thanks for the suggestions!
