### ISSUE TITLE
What license is this project? (also note - someone has copied one or more of your files verbatim)

### ISSUE THREAD

**Issue by ahungry** [LanternEQ/LanternExtractor#24]
See: https://github.com/smasherprog/EqTool/tree/main/src/Services/WLD

**Comment by danwilkins** [comment]
Thanks for letting us know. We'll get a license up!

**Comment by NathanHandley** [comment]
Hello there @danwilkins. I would very much like to include this code as a library (either as code or compiled) for the project I'm working here: https://github.com/NathanHandley/EQWOWConverter.  May I?  If so, please let me know what rules or license I should include.  If you haven't sorted something out yet, I can always just put "all rights reserved etc" type text.

**Comment by danwilkins** [comment]
License is updated. Thanks for asking and have fun!
