### ISSUE TITLE
Branch 2.0: No valid EQ files found

### ISSUE THREAD

**Issue by azereki** [LanternEQ/LanternExtractor#6]
_Edit: Built solution in debug and release. Seems like it is not finding any of the .s3d or .pfs files, or it doesn't like the directory structure._

When setting a path that is not _C:/EverQuest_, such as: _C:\Program Files (x86)\Steam\steamapps\common\Everquest F2P_ and building the solution, the application appears to fail to find the specified directory and defaults to the hardcoded value in Settings.cs.

**Attempting to change the hardcoded value results in several warnings in VS:**
![LanternEQWarnings](https://user-images.githubusercontent.com/11672598/81488181-57ea4f80-921a-11ea-8389-c378775488c3.png)

**Here is the error in the command prompt for Debug:**
![LanternCommandPrompt](https://user-images.githubusercontent.com/11672598/81488192-77817800-921a-11ea-8974-f2d280526f10.png)

**Command prompt for Release:**
![LanternReleaseNeriaka](https://user-images.githubusercontent.com/11672598/81488277-96ccd500-921b-11ea-9080-4a8ef4fa6e26.png)

**Comment by danwilkins** [comment]
Interesting. Will take a look into this.

**Comment by azereki** [comment]
Looked over your code to see if I could figure out how to fix this myself, but a bit out of my depth. Happy to help debug further if needed!

**Comment by danwilkins** [comment]
If the extractor is built in debug mode, it will use the hardcoded zone name found in `LanternExtractor.cs`. If it's release, it will use the command line arguments. But I am still not sure what's causing the path issue.

Thanks for the offer. I will probably get around to it this weekend. Aiming to release a zone viewer sometime next week, and then version 0.2 of the extractor after that.

**Comment by vermadas** [comment]
I was getting this in 0.2 as well when using Obj export format. The console output was a red herring - in the log file it showed a null reference error in  MeshExporter.cs.

The problem is here:
https://github.com/danwilkins/LanternExtractor/blob/8e87d6e09bc09ffc967f0dca43021995ce8af067/LanternExtractor/EQ/Wld/Exporters/MeshExporter.cs#L27

If using anything other than the default "Intermediate" export format, the three TextAssetWriters are unassigned.

**Comment by Impact1983** [comment]
stupid question but did you try a / at the end?  That fixed it for me.
