### ISSUE TITLE
Dev Branch (0.2) Features ?

### ISSUE THREAD

**Issue by dephora** [LanternEQ/LanternExtractor#7]
Really appreciate the time and effort put into this. 

I might have overlooked it but what is upcoming in 0.2 ?

**Comment by danwilkins** [comment]
Too many things to list just yet. It essentially finishes everything I have left to do regarding the EverQuest Triology client including bug fixes, handling of a lot of new data fragments and full support for character models and animations. The animations will work out of the box with Unity, and we are looking into adding FBX export support for those that want to use them elsewhere.

**Comment by danwilkins** [comment]
0.3 will focus on support for the Titanium client.

**Comment by dephora** [comment]
Awesome, what I was hoping for. Again, thanks so much for this!

**Comment by danwilkins** [comment]
@dephora Thanks for the question. We have a channel for the project on the EQClassic discord server if you ever have any questions or want to stay updated with latest progress.

**Comment by dephora** [comment]
Oh, great, yeah I'll definitely join. Appreciate it!
